# atomnames.sed : convert NAMD pdb file atom names to
# those used in Amber
#
# (c) Cameron Abrams
# Drexel University
# Chemical and Biological Engineering
#
# All
s/ HN / H  /

# N-terminal residue
s/ HT1/ H1 /
s/ HT2/ H2 /
s/ HT3/ H3 /
s/ HN1/ H1 /
s/ HN2/ H2 /
s/ HN3/ H3 /
s/ H2  PRO/ H3  PRO/
s/ H1  PRO/ H2  PRO/

# C-terminal residue
s/ OT2/ O  /
s/ OT1/ OXT/

# Alanine
s/ HB1 ALA/1HB  ALA/
s/ HB2 ALA/2HB  ALA/
s/ HB3 ALA/3HB  ALA/

# Valine
s/HG11 VAL/1HG1 VAL/
s/HG12 VAL/2HG1 VAL/
s/HG13 VAL/3HG1 VAL/
s/HG21 VAL/1HG2 VAL/
s/HG22 VAL/2HG2 VAL/
s/HG23 VAL/3HG2 VAL/

# Leucine
s/ HB1 LEU/WXYZ LEU/
s/ HB2 LEU/3HB  LEU/
s/WXYZ LEU/2HB  LEU/
s/HD11 LEU/1HD1 LEU/
s/HD12 LEU/2HD1 LEU/
s/HD13 LEU/3HD1 LEU/
s/HD21 LEU/1HD2 LEU/
s/HD22 LEU/2HD2 LEU/
s/HD23 LEU/3HD2 LEU/

# Isoleucine
s/1HG1 ILE/WXYZ ILE/
s/2HG1 ILE/3HG1 ILE/
s/WXYZ ILE/2HG1 ILE/
s/HG11 ILE/WXYZ ILE/
s/HG12 ILE/3HG1 ILE/
s/WXYZ ILE/2HG1 ILE/
s/ CD  ILE/ CD1 ILE/
s/ HD1 ILE/1HD1 ILE/
s/ HD2 ILE/2HD1 ILE/
s/ HD3 ILE/3HD1 ILE/
s/HG21 ILE/1HG2 ILE/
s/HG22 ILE/2HG2 ILE/
s/HG23 ILE/3HG2 ILE/

# Proline
s/ HB1 PRO/WXYZ PRO/
s/ HB2 PRO/3HB  PRO/
s/WXYZ PRO/2HB  PRO/
s/ HG1 PRO/WXYZ PRO/
s/ HG2 PRO/3HG  PRO/
s/WXYZ PRO/2HG  PRO/
s/ HD1 PRO/WXYZ PRO/
s/ HD2 PRO/3HD  PRO/
s/WXYZ PRO/2HD  PRO/

# Phenylalanine
s/ HB1 PHE/WXYZ PHE/
s/ HB2 PHE/3HB  PHE/
s/WXYZ PHE/2HB  PHE/

# Tryptophan
s/ HB1 TRP/WXYZ TRP/
s/ HB2 TRP/3HB  TRP/
s/WXYZ TRP/2HB  TRP/

# Methionine
s/ HB1 MET/WXYZ MET/
s/ HB2 MET/3HB  MET/
s/WXYZ MET/2HB  MET/
s/ HG1 MET/WXYZ MET/
s/ HG2 MET/3HG  MET/
s/WXYZ MET/2HG  MET/
s/ HE1 MET/1HE  MET/
s/ HE2 MET/2HE  MET/
s/ HE3 MET/3HE  MET/

# Glycine
s/ HA1 GLY/WXYZ GLY/
s/ HA2 GLY/3HA  GLY/
s/WXYZ GLY/2HA  GLY/

# Serine
s/ HB1 SER/WXYZ SER/
s/ HB2 SER/3HB  SER/
s/WXYZ SER/2HB  SER/
s/ HG1 SER/ HG  SER/

# Threonine
s/HG21 THR/1HG2 THR/
s/HG22 THR/2HG2 THR/
s/HG23 THR/3HG2 THR/
s/ HG1 THR/1HG  THR/

# Cysteine
s/ HB1 CYS/WXYZ CYS/
s/ HB2 CYS/3HB  CYS/
s/WXYZ CYS/2HB  CYS/
s/ HG1 CYS/ HG  CYS/
s/ HB1 CYX/WXYZ CYX/
s/ HB2 CYX/3HB  CYX/
s/WXYZ CYX/2HB  CYX/

# Asparagine
s/ HB1 ASN/WXYZ ASN/
s/ HB2 ASN/3HB  ASN/
s/WXYZ ASN/2HB  ASN/
s/HD21 ASN/1HD2 ASN/
s/HD22 ASN/2HD2 ASN/

# Glutamine
s/ HB1 GLN/WXYZ GLN/
s/ HB2 GLN/3HB  GLN/
s/WXYZ GLN/2HB  GLN/
s/ HG1 GLN/WXYZ GLN/
s/ HG2 GLN/3HG  GLN/
s/WXYZ GLN/2HG  GLN/
s/HE21 GLN/1HE2 GLN/
s/HE22 GLN/2HE2 GLN/

# Tyrosine
s/ HB1 TYR/WXYZ TYR/
s/ HB2 TYR/3HB  TYR/
s/WXYZ TYR/2HB  TYR/
s/ HD1 TYR/1HD  TYR/
s/ HD2 TYR/2HD  TYR/

# Histidine HIS
s/HIS/HIP/
s/ HD1 HIP/1HD  HIP/
s/ HB1 HIP/WXYZ HIP/
s/ HB2 HIP/3HB  HIP/
s/WXYZ HIP/2HB  HIP/
s/HSD/HID/
s/ HD1 HID/1HD  HID/
s/ HB1 HID/WXYZ HID/
s/ HB2 HID/3HB  HID/
s/WXYZ HID/2HB  HID/
s/HSE/HIE/
s/ HB1 HIE/WXYZ HIE/
s/ HB2 HIE/3HB  HIE/
s/WXYZ HIE/2HB  HIE/

# Lysine
s/ HB1 LYS/WXYZ LYS/
s/ HB2 LYS/3HB  LYS/
s/WXYZ LYS/2HB  LYS/
s/ HG1 LYS/WXYZ LYS/
s/ HG2 LYS/3HG  LYS/
s/WXYZ LYS/2HG  LYS/
s/ HD1 LYS/WXYZ LYS/
s/ HD2 LYS/3HD  LYS/
s/WXYZ LYS/2HD  LYS/
s/ HE1 LYS/WXYZ LYS/
s/ HE2 LYS/3HE  LYS/
s/WXYZ LYS/2HE  LYS/
s/ HZ1 LYS/1HZ  LYS/
s/ HZ2 LYS/2HZ  LYS/
s/ HZ3 LYS/3HZ  LYS/

# Arginine
s/ HB1 ARG/WXYZ ARG/
s/ HB2 ARG/3HB  ARG/
s/WXYZ ARG/2HB  ARG/
s/ HG1 ARG/WXYZ ARG/
s/ HG2 ARG/3HG  ARG/
s/WXYZ ARG/2HG  ARG/
s/ HD1 ARG/WXYZ ARG/
s/ HD2 ARG/3HD  ARG/
s/WXYZ ARG/2HD  ARG/
s/HH11 ARG/1HH1 ARG/
s/HH12 ARG/2HH1 ARG/
s/HH21 ARG/1HH2 ARG/
s/HH22 ARG/2HH2 ARG/

# Aspartate
s/ HB1 ASP/WXYZ ASP/
s/ HB2 ASP/3HB  ASP/
s/WXYZ ASP/2HB  ASP/

# Glutamate
s/ HB1 GLU/WXYZ GLU/
s/ HB2 GLU/3HB  GLU/
s/WXYZ GLU/2HB  GLU/
s/ HG1 GLU/WXYZ GLU/
s/ HG2 GLU/3HG  GLU/
s/WXYZ GLU/2HG  GLU/



